package parser

type NodeKind int

const (
	ROOT NodeKind = iota

	FACTOR_LITERAL_NUMBER
	FACTOR_LITERAL_STRING
	FACTOR_IDENTIFIER
	FACTOR_EXPRESSION
	FACTOR_NEGATE
	FACTOR_FUNCTION_CALL

	EXPRESSION_ADD
	EXPRESSION_SUBTRACT
	EXPRESSION_MULTIPLY
	EXPRESSION_DIVIDE

	STATEMENT_BLOCK
	STATEMENT_RETURN
	STATEMENT_LET_DECLARATION
	STATEMENT_CONST_DECLARATION
	STATEMENT_LET_ASSIGN
	STATEMENT_FUNCTION_DECLARATION
	STATEMENT_WHILE_LOOP
	STATEMENT_IF

	RETURN_TYPE_NUMBER
	RETURN_TYPE_STRING
	RETURN_TYPE_BOOL

	PARAMETER_TYPE_NUMBER
	PARAMETER_TYPE_STRING
	PARAMETER_TYPE_BOOL

	TYPE_NUMBER
	TYPE_STRING
	TYPE_BOOL

	END
)

type Node struct {
	Kind     NodeKind
	Value    string
	Children []Node
}
